"""從 ACTIONsub_DRUG_PREPARATION.ERB 抽取的原文；key 為行號。由 tools/extract_drug_text.py 重建。"""

TEXT = {
    18: ('PRINTL', 'ロボっ娘ナース：'),
    19: ('PRINTL', '「ようこそメディカルルームへ」（ペコリ）'),
    20: ('PRINTL', '「ここでは資金や触手の欠片を消費して特定素質の消去などを行うことができます」'),
    22: ('PRINTL', '「本日のご用件は何でしょうか？」'),
    24: ('PRINTL', '「今回はどなたを治療致しましょうか？」'),
    26: ('PRINTL', '「健康には気を付けてくださいね」'),
    28: ('PRINTL', '「何かお手伝いできることはございますか？」'),
    30: ('PRINTL', ''),
    31: ('PRINTFORML', '<< 触手の欠片の所持数：{FLAG:200}個 >>'),
    32: ('PRINTFORML', '<< 避妊用ピル所持数  ：{FLAG:201}個 >>'),
    34: ('PRINTFORML', '[0]   [触手の虜]の消去 - 触手の欠片5個消費'),
    35: ('PRINTFORML', '[1]   [ふたなり]の消去 - 触手の欠片2個消費'),
    36: ('PRINTFORML', '[2]   [母乳体質]の消去 - 触手の欠片2個消費'),
    37: ('PRINTFORML', '[3]   [寄生]の消去\u3000\u3000 - 触手の欠片2個消費'),
    38: ('PRINTFORML', '[4]   [苗床化]の消去\u3000 - 触手の欠片2個消費'),
    39: ('PRINTFORML', '[5]   [膨乳]の治療\u3000 \u3000- 触手の欠片2個消費'),
    40: ('PRINTL', ''),
    41: ('PRINTFORML', '[10]   妊娠検査薬                     - 50$'),
    42: ('PRINTFORML', '[11]   胎内精密検査                   - 250$'),
    43: ('PRINTFORML', '[12]   堕胎手術（入院中のキャラも可） - 7000$'),
    44: ('PRINTFORML', '[13]   避妊用ピルの購入               - 125$'),
    45: ('PRINTFORML', '[14]   避妊用ピルの処方'),
    47: ('PRINTFORML', '[15]   ロボっ子のメンテナンス'),
    48: ('PRINTL', ''),
    49: ('PRINTFORML', '[20]   淫紋の治療                     - 触手の欠片10個消費'),
    50: ('PRINTFORML', '[21]   淫紋の進行を遅らせる           - 1250$'),
    51: ('PRINTL', ''),
    52: ('PRINTFORML', '[30]   性徴促進薬                     - 触手の欠片1個消費'),
    53: ('PRINTFORML', '[31]   性徴停滞薬                     - 触手の欠片1個消費'),
    54: ('PRINTL', ''),
    58: ('PRINTFORML', '[100]  ロボっ子の新規加入\u3000\u3000\u3000\u3000\u3000 \u3000- 50000$'),
    60: ('PRINTL', ''),
    61: ('PRINTFORML', '[999] やめる'),
    68: ('PRINTW', '触手の欠片が足りません'),
    76: ('PRINTW', '触手の欠片が足りません'),
    84: ('PRINTW', '触手の欠片が足りません'),
    92: ('PRINTW', '触手の欠片が足りません'),
    100: ('PRINTW', '触手の欠片が足りません'),
    108: ('PRINTW', '触手の欠片が足りません'),
    116: ('PRINTW', '資金が足りません'),
    124: ('PRINTW', '資金が足りません'),
    132: ('PRINTW', '資金が足りません'),
    140: ('PRINTW', '資金が足りません'),
    143: ('PRINTL', ''),
    144: ('PRINTFORML', '\u3000＊\u3000避妊用ピルの購入\u3000＊'),
    145: ('PRINTFORML', '避妊用ピルは１つで半日間だけ妊娠を防ぐ効果があります'),
    146: ('PRINTFORML', 'ただし、触手の受精能力が強力すぎるため触手に対しては効果がありません'),
    147: ('PRINTFORML', '\u3000購入数を入力してください(1-{MONEY / 125}個)'),
    148: ('PRINTFORML', '\u3000(0か負の数入力でキャンセル)'),
    152: ('PRINTFORML', '避妊用ピルを{LOCAL}個購入で${125 * LOCAL}になります。宜しいですか？'),
    153: ('PRINTFORML', '[0]はい'),
    154: ('PRINTFORML', '[1]いいえ'),
    166: ('PRINTW', '資金が足りません'),
    178: ('PRINTW', '避妊用ピルを所持していません'),
    189: ('PRINTW', '触手の欠片が足りません'),
    197: ('PRINTW', '資金が足りません'),
    205: ('PRINTW', '触手の欠片が足りません'),
    213: ('PRINTW', '触手の欠片が足りません'),
    221: ('PRINTL', '触手のバイオマスを利用して人体の機能を回復する技術を開発中です'),
    222: ('PRINTW', '（より高いレベルの触手研究が必要です！）'),
    225: ('PRINTL', '現在の研究レベルでは、'),
    226: ('PRINTL', '触手からのバイオマスは人体の機能を回復するために使用でき、'),
    227: ('PRINTL', '【四肢欠損】の場合は$25,000と触手の残骸40消費が必要となります。'),
    228: ('PRINTL', 'そして触手との【共生】状態となります'),
    229: ('PRINTL', '本当に手術をしてよろしいですか？'),
    230: ('PRINTL', '[0]はい'),
    231: ('PRINTL', '[1]いいえ'),
    236: ('PRINTW', '手術に必要な資金が不足しています。'),
    239: ('PRINTW', '手術に必要な触手の欠片が不足しています。'),
    251: ('PRINTL', '「おや、手術しないのですか？\u3000それなら別の選択肢も提示できますよ」'),
    252: ('PRINTL', 'ロボっ娘ナースを脇に押し退け、白衣の少女研究者が現れた'),
    253: ('PRINTL', ''),
    254: ('PRINTL', '「……というのもですね。実は現在の肥大化する運営予算とリソース、到底持続可能な状態ではありません。'),
    255: ('PRINTL', '\u3000たとえば【四肢欠損】した魔法少女のケア、あれには多額のリソースを浪費する必要があります。'),
    256: ('PRINTW', '\u3000ご存知でしょう、正義感の強い彼女たちがどれほど苦しんでいるか……」'),
    257: ('PRINTL', ''),
    258: ('PRINTL', '「ねえ、あのような生き地獄を続けさせるくらいなら、いっそ「再利用」したらどうですか？'),
    259: ('PRINTL', '\u3000あるいはスポンサーを増やすために「特別」なショーを企画できるかもしれませんが…どうです？」'),
    260: ('PRINTL', ''),
    261: ('PRINTL', '[0]……'),
    262: ('PRINTL', '[1]仲間を売るなんてとんでもない！'),
    271: ('PRINTW', '正しい値を入力してください'),
    275: ('PRINTW', '正しい値を入力してください'),
    282: ('PRINTW', '資金が足りません'),
    286: ('PRINTFORML', ' 所持金： {MONEY}$'),
    288: ('PRINTL', '資金を50000$支払いロボっ子を新規加入させます。'),
    289: ('PRINTL', 'キャンセルはできませんが、よろしいですか？'),
    290: ('PRINTL', '[0]性別：♀で確定'),
    291: ('PRINTL', '[1]性別：♂で確定'),
    292: ('PRINTL', ''),
    293: ('PRINTL', '[99]キャンセル'),
    297: ('PRINTW', '加入要請を行いました。'),
    300: ('PRINTL', ''),
    301: ('PRINTW', '加入する新規キャラクターの設定を行います。'),
    325: ('PRINTFORML', '『%CALLNAME%』にフィートを設定しますか？'),
    326: ('PRINTFORML', '[0]はい'),
    327: ('PRINTFORML', '[1]いいえ'),
    328: ('PRINTFORML', '[2]ランダムに設定する'),
    346: ('PRINTFORML', '%TALENTNAME:(RACE)%'),
    349: ('PRINTL', ''),
    350: ('PRINTL', '(取得可能フィート)          選択'),
    355: ('PRINT', '\u3000★'),
    357: ('PRINT', '\u3000☆'),
    359: ('PRINTFORM', '%TALENTNAME:(LOCAL + LOCAL:2),22,LEFT%  [{LOCAL}]  '),
    362: ('PRINT', '◎'),
    364: ('PRINTPLAIN', ' 固定取得'),
    367: ('PRINT', '○'),
    370: ('PRINT', '×'),
    372: ('PRINTL', ''),
    374: ('PRINTL', ''),
    375: ('PRINTFORML', '選択したフィート({FEAT_NUM}/3)'),
    378: ('PRINTL', '[0]決定'),
    387: ('PRINTL', ''),
    408: ('PRINTFORML', '%PRINT_CALLNAME(TARGET)%にはフィートを設定しません'),
    409: ('PRINTW', ''),
    415: ('PRINTFORML', 'ランダムにフィートを設定しました'),
    416: ('PRINTW', ''),
    423: ('PRINTL', ''),
    424: ('PRINTFORML', '『%CALLNAME%』を{TARGET}人目のメンバーとして迎え入れました。'),
    425: ('PRINTFORML', '『%CALLNAME%』は控えメンバーに加えられます。'),
    429: ('PRINTW', ''),
    439: ('PRINTL', '正しい値を入力してください'),
    442: ('PRINTL', ''),
    443: ('PRINTL', ''),
    449: ('PRINTL', ''),
    450: ('PRINTL', '誰を選びますか？'),
    459: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    460: ('PRINTL', ''),
    465: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    467: ('PRINTFORM', '\u3000\u3000\u3000後天ふたなり'),
    469: ('PRINTFORM', '\u3000\u3000\u3000寄生ふたなり'),
    471: ('PRINTFORM', '\u3000\u3000\u3000後天ふたなり(変身時)'),
    473: ('PRINTFORM', '\u3000\u3000\u3000寄生ふたなり(変身時)'),
    474: ('PRINTL', ''),
    479: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    480: ('PRINTL', ''),
    486: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    487: ('PRINTL', ''),
    492: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    493: ('PRINTL', ''),
    498: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    500: ('PRINT', ' \u3000\u3000\u3000貧乳'),
    502: ('PRINT', ' \u3000\u3000\u3000奇乳'),
    504: ('PRINT', ' \u3000\u3000\u3000魔乳'),
    506: ('PRINT', ' \u3000\u3000\u3000超乳'),
    508: ('PRINT', ' \u3000\u3000\u3000爆乳'),
    510: ('PRINT', ' \u3000\u3000\u3000巨乳'),
    512: ('PRINT', ' \u3000\u3000\u3000普乳'),
    515: ('PRINT', ' \u3000\u3000\u3000貧乳(変身時)'),
    517: ('PRINT', ' \u3000\u3000\u3000奇乳(変身時)'),
    519: ('PRINT', ' \u3000\u3000\u3000魔乳(変身時)'),
    521: ('PRINT', ' \u3000\u3000\u3000超乳(変身時)'),
    523: ('PRINT', ' \u3000\u3000\u3000爆乳(変身時)'),
    525: ('PRINT', ' \u3000\u3000\u3000巨乳(変身時)'),
    527: ('PRINT', ' \u3000\u3000\u3000普乳(変身時)'),
    529: ('PRINTL', ''),
    534: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    535: ('PRINTL', ''),
    540: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    541: ('PRINTL', ''),
    546: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    547: ('PRINTL', ''),
    552: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT,24,LEFT%\u3000ピル処方数：({CFLAG:CCOUNT:241})'),
    553: ('PRINTL', ''),
    558: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    559: ('PRINTL', ''),
    564: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    565: ('PRINTL', ''),
    569: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    570: ('PRINTL', ''),
    575: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    576: ('PRINTL', ''),
    581: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    582: ('PRINTL', ''),
    587: ('PRINTFORM', '[{CCOUNT}] %CALLNAME:CCOUNT%'),
    588: ('PRINTL', ''),
    592: ('PRINTFORML', '[999]キャラ選択をやめる'),
    598: ('PRINTL', '正しい値を入力してください'),
    603: ('PRINTL', '正しい値を入力してください'),
    611: ('PRINTFORML', '記憶調整薬を投与し、'),
    612: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:150%を消去しました'),
    613: ('PRINTFORML', '%CALLNAME:RESULT%の触手中毒が初期化されました'),
    617: ('PRINTL', '正しい値を入力してください'),
    622: ('PRINTFORML', '抗触手薬を投与し、寄生部位を治療しました'),
    624: ('PRINTFORML', 'ホルモンバランス調整剤を投与し、クリトリスを正常に戻しました'),
    627: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:300%を消去しました'),
    632: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:404%を消去しました'),
    638: ('PRINTL', '正しい値を入力してください'),
    643: ('PRINTFORML', 'ホルモンバランス調整剤を投与し、母乳を出なくしました'),
    644: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:1%を消去しました'),
    648: ('PRINTL', '正しい値を入力してください'),
    653: ('PRINTFORML', '抗触手薬を投与し、寄生部位を除去しました'),
    654: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:160%を消去しました'),
    658: ('PRINTL', '正しい値を入力してください'),
    663: ('PRINTFORML', '抗触手薬を投与し、子宮の異常を治療しました'),
    664: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:161%を消去しました'),
    668: ('PRINTL', '正しい値を入力してください'),
    672: ('PRINTFORML', 'ホルモンバランス調整剤を投与し、胸の張りを治療しました'),
    681: ('PRINTFORM', '変身時の'),
    697: ('PRINTFORML', '%CALLNAME:RESULT%の胸を小さくしました'),
    699: ('PRINTFORML', '%CALLNAME:RESULT%の胸を正常に戻しました'),
    706: ('PRINTL', '正しい値を入力してください'),
    712: ('PRINTFORML', '妊娠検査薬の反応は陰性です。'),
    713: ('PRINTFORML', '※妊娠から日が浅いと検査薬が反応しないことがあります。'),
    715: ('PRINTFORML', '妊娠検査薬の反応は陽性です。'),
    717: ('PRINTFORML', '%CALLNAME:RESULT%の妊娠が発覚しました！'),
    724: ('PRINTL', '正しい値を入力してください'),
    730: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮は寄生かつ苗床化されており、'),
    731: ('PRINTFORML', '例え人間相手による妊娠でも異常が発生する可能性があるようです。'),
    733: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮は触手生物の細胞に寄生されており、'),
    734: ('PRINTFORML', '例え人間相手による妊娠でも正常な子供が生まれない可能性があります。'),
    736: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮は触手生物によって苗床化されており、'),
    737: ('PRINTFORML', '異常に出産が早まる可能性があるようです。'),
    739: ('PRINTFORML', '%CALLNAME:RESULT%さんには妊娠可能な子宮がありません。'),
    740: ('PRINTFORML', '解剖学的に妊娠・出産することはあり得ません。'),
    742: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮の機能には何らかの異常があるようです。'),
    743: ('PRINTFORML', 'おそらく妊娠・出産することは難しいでしょう。'),
    745: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮には特に異常は見当たりませんでした。'),
    746: ('PRINTFORML', 'しかし肉体が未成熟のため、まだ妊娠・出産はできないでしょう。'),
    748: ('PRINTFORML', '%CALLNAME:RESULT%さんの子宮には特に異常は見当たりませんでした。'),
    749: ('PRINTFORML', '正常に妊娠・出産することができるでしょう。'),
    751: ('PRINTL', ''),
    753: ('PRINT', 'また、'),
    755: ('PRINTFORML', '精密検査の結果、%CALLNAME:RESULT%さんの胎内に妊娠の兆候が見つかりました。'),
    760: ('PRINTFORML', '%CALLNAME:RESULT%さんの胎内に宿っているのは触手の幼体{CFLAG:RESULT:227}匹のようです。'),
    762: ('PRINTL', '成長速度的に、すぐにでも産まれて来そうです。'),
    764: ('PRINTL', '産まれてくるまで、まだ数日かかりそうです。'),
    766: ('PRINTL', '現在は出産に備えて入院中です。'),
    768: ('PRINTL', 'そろそろ入院の準備が必要かもしれません。'),
    771: ('PRINTFORML', '%CALLNAME:RESULT%さんの胎内に宿っているのはヒトの胎児のようです。'),
    773: ('PRINTL', '成長速度が異常に早く、すぐにでも産まれて来そうです。'),
    775: ('PRINTL', '信じられない速度で成長しており、あと数日で産まれそうです。'),
    777: ('PRINTL', '現在は出産に備えて入院中です。'),
    779: ('PRINTL', 'そろそろ入院の準備が必要かもしれません。'),
    782: ('PRINTFORM', '%CALLNAME:RESULT%さんの胎内に宿っているのは'),
    784: ('PRINTL', 'ヒトの受精卵のようです。'),
    785: ('PRINTL', 'まだ着床した段階ですが、妊娠は成立しています。'),
    787: ('PRINTL', 'ヒトの受精卵のようです。'),
    788: ('PRINTL', '胎嚢が確認できます。経過は順調のようです。'),
    790: ('PRINTL', 'ヒトの胎芽のようです。'),
    791: ('PRINTL', 'しっかりと心拍を打っている様子が確認されています。'),
    793: ('PRINTL', 'ヒトの胎児のようです。'),
    794: ('PRINTL', 'まだサイズは小さいですが、ヒトの形になってきています。'),
    796: ('PRINTL', 'ヒトの胎児のようです。'),
    797: ('PRINTL', 'はっきりと赤ん坊の姿になっているのが分かります。'),
    799: ('PRINTL', 'ヒトの胎児のようです。'),
    800: ('PRINTL', '赤ちゃんは元気です。すくすくと成長しているようです。'),
    802: ('PRINTL', 'ヒトの胎児のようです。'),
    803: ('PRINTL', '経過は良好で母子ともに健康です。'),
    805: ('PRINTL', 'ヒトの胎児のようです。'),
    806: ('PRINTL', '時折腹を蹴ったり、活発に動いている様子が見られます。'),
    808: ('PRINTL', 'ヒトの胎児のようです。'),
    809: ('PRINTL', 'もう出産間近です。いつでも手術室に移動できるよう準備しておきましょう。'),
    811: ('PRINTFORML', '(妊娠{CFLAG:RESULT:222 * 20 / 28}／40週目相当)'),
    813: ('PRINTFORML', '%CALLNAME:RESULT%さんの胎内に妊娠の兆候は見つかりませんでした。'),
    818: ('PRINTL', '正しい値を入力してください'),
    832: ('PRINTFORML', '%CALLNAME:RESULT%の堕胎手術は無事に成功しました'),
    834: ('PRINTFORML', '%CALLNAME:RESULT%が戦線に復帰しました'),
    842: ('PRINTL', '正しい値を入力してください'),
    846: ('PRINTFORML', '半日ごとに処方したピルを自動で1個消費します'),
    847: ('PRINTFORML', '%CALLNAME:LOCAL%に処方する避妊用ピルの量を選択してください(0-{FLAG:201 + CFLAG:LOCAL:241})'),
    848: ('PRINTFORML', '<< 現在の処方数  ：残り{CFLAG:LOCAL:241}個 >>\u3000\u3000(負の数でキャンセル)'),
    856: ('PRINTFORML', '%CALLNAME:LOCAL%によるピルの使用を中止させました'),
    858: ('PRINTFORML', '%CALLNAME:LOCAL%へのピルの処方数を{RESULT}個としました'),
    861: ('PRINTFORML', '%CALLNAME:LOCAL%へのピルの処方数を変更せず{CFLAG:LOCAL:241}個のままとしました'),
    863: ('PRINTL', '正しい値を入力してください'),
    869: ('PRINTL', '正しい値を入力してください'),
    875: ('PRINTL', 'スケジュールの設定'),
    877: ('PRINTFORML', '%CALLNAME:LOCAL%に対して行う処置を選択してください'),
    880: ('PRINTFORML', '[0]パーツ交換\u3000\u3000\u3000（疲労回復：小）\u3000\u3000\u3000\u3000$500'),
    884: ('PRINTFORML', '[1]集中メンテナンス（疲労回復：大）\u3000\u3000 \u3000 $1500'),
    888: ('PRINTFORML', '[2]オーバーホール\u3000（疲労完全回復）\u3000\u3000\u3000  $5500'),
    891: ('PRINTFORML', '[3]人工子宮を取り外す'),
    893: ('PRINTFORML', '[3]人工子宮を取り付ける'),
    895: ('PRINTFORML', '[999]戻る'),
    900: ('PRINTW', '資金が足りません'),
    908: ('PRINTL', ''),
    909: ('PRINTFORML', '%CALLNAME:LOCAL%に対してパーツ交換を行いました'),
    910: ('PRINTW', ''),
    915: ('PRINTW', '資金が足りません'),
    923: ('PRINTL', ''),
    924: ('PRINTFORML', '%CALLNAME:LOCAL%に対して集中メンテナンスを行いました'),
    925: ('PRINTW', ''),
    930: ('PRINTW', '資金が足りません'),
    936: ('PRINTL', ''),
    937: ('PRINTFORML', '%CALLNAME:LOCAL%に対してオーバーホールを行いました'),
    938: ('PRINTW', ''),
    943: ('PRINTL', ''),
    945: ('PRINTFORML', '%CALLNAME:LOCAL%の人工子宮を取り外しました'),
    946: ('PRINTFORML', '%CALLNAME:LOCAL%は不妊になります'),
    949: ('PRINTFORML', '%CALLNAME:LOCAL%に人工子宮を取り付けました'),
    950: ('PRINTFORML', '%CALLNAME:LOCAL%は妊娠可能になります'),
    953: ('PRINTW', ''),
    956: ('PRINTL', 'メディカルルームに戻ります'),
    963: ('PRINTL', '正しい値を入力してください'),
    969: ('PRINTFORML', '%CALLNAME:RESULT%の身体から瘴気が抜けていく・・・'),
    970: ('PRINTFORML', '%CALLNAME:RESULT%の淫紋を消去しました'),
    974: ('PRINTL', '正しい値を入力してください'),
    977: ('PRINTFORML', '現在の状態では副作用が強くなり過ぎるため、瘴気中和剤を投与できません'),
    978: ('PRINTFORML', 'しばらくして症状が酷くなったらまたお越しください'),
    983: ('PRINTFORML', '%CALLNAME:RESULT%に瘴気中和剤を注射したが、完治はしなかった・・・'),
    984: ('PRINTFORML', '%CALLNAME:RESULT%の淫紋の進行度が減少しました'),
    988: ('PRINTL', '正しい値を入力してください'),
    993: ('PRINTFORML', '性徴促進薬を投与しました'),
    995: ('PRINTFORML', '性徴促進薬を投与しました'),
    998: ('PRINTFORML', '%CALLNAME:RESULT%の%TALENTNAME:4%を消去しました'),
    1000: ('PRINTFORML', '%CALLNAME:RESULT%は射精できるようになりました'),
    1002: ('PRINTFORML', '%CALLNAME:RESULT%は妊娠できるようになりました'),
    1007: ('PRINTFORML', '%CALLNAME:RESULT%の肉体的性徴が再び始まりました'),
    1013: ('PRINTL', '正しい値を入力してください'),
    1018: ('PRINTFORML', '性徴停滞薬を投与しました'),
    1019: ('PRINTFORML', '%CALLNAME:RESULT%の肉体的性徴が止まりました'),
    1024: ('PRINTL', '正しい値を入力してください'),
    1031: ('PRINTW', '. . .'),
    1032: ('PRINTW', '. . .'),
    1033: ('PRINTW', '. . .'),
    1034: ('PRINTFORML', '触手のバイオマスを利用して手足を形成し、'),
    1035: ('PRINTFORMW', 'それらが%CALLNAME:RESULT%の身体に接続された。'),
    1036: ('PRINTFORML', '%CALLNAME:RESULT%の手足は完全に復元されました'),
    1037: ('PRINTFORMW', '代償として、%CALLNAME:RESULT%は%TALENTNAME:163%を獲得しました'),
    1041: ('PRINTW', ''),
}
