"""從 ACTIONsub_TSUIKAYOUSEI_NORMAL.ERB 抽取的原文；key 為行號。由 tools/extract_recruitment_text.py 重建。"""

TEXT = {
    10: ('PRINTFORML', 'これまでに追加で加入させた人数 {FLAG:250}人'),
    11: ('PRINTL', '新しいキャラクターを新規加入させます。'),
    12: ('PRINTL', 'キャンセルはできませんが、よろしいですか？'),
    13: ('PRINTL', '[0]性別：♀で確定'),
    14: ('PRINTL', '[1]性別：♂で確定'),
    15: ('PRINTL', '[2]ランダム生成する'),
    16: ('PRINTL', ''),
    17: ('PRINTL', '[99]キャンセル'),
    22: ('PRINTW', '加入要請を行いました。'),
    25: ('PRINTL', ''),
    30: ('PRINTW', '加入する新規キャラクターの設定を行います。'),
    45: ('PRINTFORML', '『%CALLNAME%』にフィートを設定しますか？'),
    46: ('PRINTFORML', '[0]はい'),
    47: ('PRINTFORML', '[1]いいえ'),
    48: ('PRINTFORML', '[2]ランダムに設定する'),
    66: ('PRINTFORML', '%TALENTNAME:(RACE)%'),
    69: ('PRINTL', ''),
    70: ('PRINTL', '(取得可能フィート)          選択'),
    75: ('PRINT', '\u3000★'),
    77: ('PRINT', '\u3000☆'),
    79: ('PRINTFORM', '%TALENTNAME:(LOCAL + LOCAL:2),22,LEFT%  [{LOCAL}]  '),
    82: ('PRINT', '◎'),
    84: ('PRINTPLAIN', ' 固定取得'),
    87: ('PRINT', '○'),
    90: ('PRINT', '×'),
    92: ('PRINTL', ''),
    94: ('PRINTL', ''),
    95: ('PRINTFORML', '選択したフィート({FEAT_NUM}/3)'),
    98: ('PRINTL', '[0]決定'),
    107: ('PRINTL', ''),
    128: ('PRINTFORML', '%PRINT_CALLNAME(TARGET)%にはフィートを設定しません'),
    129: ('PRINTW', ''),
    135: ('PRINTFORML', 'ランダムにフィートを設定しました'),
    136: ('PRINTW', ''),
    143: ('PRINTL', ''),
    144: ('PRINTFORML', '『%CALLNAME%』を{TARGET}人目のメンバーとして迎え入れました。'),
    146: ('PRINTFORML', '『%CALLNAME%』は控えメンバーに加えられます。'),
    153: ('PRINTW', ''),
    160: ('PRINTL', ''),
    161: ('PRINTL', ''),
}
